import {
  RadioTower,
  Activity,
  Route,
  ClipboardCheck,
  Link2,
  Monitor,
  Building2,
  Headphones,
  Users,
  GraduationCap,
  MapPin,
  Settings,
  Smartphone,
  Globe,
  Zap,
  TrendingUp,
  ShieldCheck,
  Target,
} from "lucide-react";

export const ICONS = {
  "radio-tower": RadioTower,
  activity: Activity,
  route: Route,
  "clipboard-check": ClipboardCheck,
  "link-2": Link2,
  monitor: Monitor,
  "building-2": Building2,
  headphones: Headphones,
  users: Users,
  "graduation-cap": GraduationCap,
  "map-pin": MapPin,
  settings: Settings,
  smartphone: Smartphone,
  globe: Globe,
  zap: Zap,
  "trending-up": TrendingUp,
  "shield-check": ShieldCheck,
  target: Target,
};
